apiVersion: v1
name: mlrun-ce
version: 0.6.3-rc23
appVersion: 1.6.4
description: MLRun Open Source Stack
home: https://iguazio.com
icon: https://www.iguazio.com/wp-content/uploads/2019/10/Iguazio-Logo.png
sources: []
maintainers:
  - name: Adam Melnick
    email: adamm@iguazio.com
